### ISSUE TITLE
Immediate pre-deployment TODO

### ISSUE THREAD

**Issue by safi-manar** [safi-manar/SensorInference#1]
Use this post to keep track of minor tasks that need to be done immediately before deployment.
This list is for **minor** changes from dev mode to deployment mode, not large-scale bugs / implementation ideas.

TODO
- Set appropriate `TimeConstants`
- Set Google Form to have proper deployment questions as required.
- Empty Firebase dev data

**Comment by io-reyes** [comment]
We're in pilot deployment now. These are done.
