### ISSUE TITLE
First auto-approval not happening

### ISSUE THREAD

**Issue by io-reyes** [safi-manar/SensorInference#19]
During the MTURK pilot deployment, the first assignment was not automatically approved. Identify root cause and fix.

**Comment by safi-manar** [comment]
@io-reyes 
Let's see if this still happens on next pilot.

**Comment by io-reyes** [comment]
An update on this. It's not that the first auto-approval is not happening. It's _only one_ auto-approval happening when the script should issue more than one in a run. I'll have to debug the script to figure this out.
