### ISSUE TITLE
Advanced Logging

### ISSUE THREAD

**Issue by safi-manar** [safi-manar/SensorInference#20]
Notification System:
https://firebase.google.com/docs/notifications/android/console-device#access_the_registration_token

FirebaseInstanceID.getToken()

**Comment by safi-manar** [comment]
82ae71b6b46a981aa21a2128078e9238683c93f9

Seems like sp_dump is being reported every 5 minutes. Should be on key events, not on every push... Some preference update is triggering the logging but should be disabled.

**Comment by io-reyes** [comment]
We'll keep this periodic reporting behavior. It's kind of useful for debugging.
